services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  hasnol-api:
    container_name: hasnol-api
    image: hasnolm7/hasnol-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped
  hasnol-react:
    container_name: hasnol-react
    image: hasnolm7/hasnol-react
    build:
      context: frontend/react
    ports:
      - "3000:5173"
    depends_on:
      - hasnol-api
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: